### ISSUE TITLE
Point to result examples clearly

### ISSUE THREAD

**Issue by ebugden** [riley-v/4F90-Project#2]
People want to have an idea of what the project does before they decide to explore the implementation or the code. This should be front and center otherwise people risk not realizing that examples exist. Possible solutions:
* Add examples of results to main project Readme
* In the main Readme, link clearly and directly to examples (ex. Add "**Result examples shown in implementation descriptions** ex.[CPU Hog results](https://github.com/riley-v/4F90-Project/tree/main/Implementations/CPU-Hog)")
   * Requires adding a "Results" header in each the implementation readme so you can link directly to the results screenshots

**Comment by riley-v** [comment]
I have updated the main README. Could someone please confirm that it does now give a clear understanding of what the project does.

**Comment by ebugden** [comment]
I think you could start with something even more concrete and concise. Other than that, looks great! Here's how I would summarize the project right at the top:

----

This project provides TraceCompass EASE scripts that highlight potentially problematic threads in TraceCompass views (example screenshot below). Threads are highlighted based on statistical metrics calculated using trace data (implementation details [here](https://github.com/riley-v/runtime-bad-smell-trace-metrics/tree/main/Implementations)). 

There are scripts for highlighting: 
* CPU Hog
* Thread swamp
* Priority Inversion
* Endless Waiting
* Blob thread

Example of view with the CPU Hog filter applied: 
![image](https://user-images.githubusercontent.com/28311615/121745912-03776a80-cad3-11eb-82df-b5a7b394f548.png)

**Comment by riley-v** [comment]
Ah ok. I have updated the description at the top of the README. I'm going to close the issue now, but feel free to reopen it if you feel its still ambiguous.

Thanks for all the help. Its great to get feedback from people outside of the project.
